server:
  port: 8888

app:
  api-path-prefix: /api/v1
  api-strip-prefix: 2

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-path-prefix}/identity/**
          filters:
            - StripPrefix=${app.api-strip-prefix}

        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-path-prefix}/profile/**
          filters:
            - StripPrefix=${app.api-strip-prefix}