server:
  port: 8083
  servlet:
    context-path: /post

spring:
  application:
    name: post_service
  data:
    mongodb:
      uri: mongodb://postuser:postpass@localhost:27017/post-service?authSource=post-service

app:
  services:
    profile: "http://localhost:8081/profile"